// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025-2026 katalvlaran

// Package core defines deterministic, thread-safe in-memory graphs and the
// foundational types (Graph/Vertex/Edge) used across lvlath.
//
// Design invariants (public contract, enforced across the codebase):
//  1. Determinism: public enumeration order is stable and documented
//     (Vertices by ID asc, Edges by Edge.ID asc, NeighborIDs by ID asc).
//  2. Sentinel errors only: exported operations return package-level sentinels
//     and are checked via errors.Is; no fmt-wrapping of those sentinels.
//  3. No hidden global state: behavior is explicit via options; no ambient randomness.
//  4. Concurrency: vertex catalog and edge/adjacency storage are protected by
//     separate RWMutexes (muVert, muEdgeAdj) to reduce contention.
//
// Notes:
//   - Graph configuration flags are set only during construction (NewGraph + GraphOption).
//     After construction they are immutable, so internal code may read them without locks
//     to avoid lock inversion in hot paths.
package core

import (
	"sync"
)

// Vertex is the canonical node record used by Graph; the unique key is Vertex.ID.
// Metadata is an opaque, caller-managed payload that the core does not interpret.
//
// Memory Policy (Aliasing & Ownership):
// - Graph query methods may return *Vertex aliases to catalog records.
// - Vertex.ID MUST be treated as immutable once the vertex is published in a Graph.
// - Metadata is a REFERENCE TYPE (map pointer).
// - Clone and view operations perform a SHALLOW COPY of this pointer.
// - Result: the source graph and its clones/views SHARE the same underlying Metadata maps.
// - The caller is responsible for deep-copying Metadata if total isolation is required.
//
// Implementation:
//   - Stage 1: Graph stores vertices in a map keyed by Vertex.ID.
//   - Stage 2: Algorithms treat Metadata as an opaque pointer; Clone is shallow.
//
// Behavior highlights:
//   - Vertex identity is stable for the lifetime of the graph.
//   - Metadata ownership belongs to the caller; core never mutates it.
//
// Inputs:
//   - ID: unique identifier within a Graph; must be non-empty.
//   - Metadata: arbitrary user payload; may be nil.
//
// Returns:
//   - N/A (data type).
//
// Errors:
//   - N/A (data type).
//
// Determinism:
//   - Vertex.ID is the stable ordering key for public enumeration.
//
// Complexity:
//   - N/A (data type).
//
// Notes:
//   - Graph.Clone copies the Metadata map pointer; callers must deep-copy if required.
//
// AI-Hints:
//   - Prefer short, stable IDs for deterministic logs and golden tests.
//   - Keep Metadata small and immutable if used concurrently.
type Vertex struct {
	// ID uniquely identifies a vertex within a single Graph instance.
	ID string

	// Metadata holds arbitrary caller-managed payload.
	// Clone/View operations shallow-copy this map pointer.
	// core does not synchronize metadata contents.
	Metadata map[string]interface{}
}

// Edge is the canonical connection record used by Graph; the unique key is Edge.ID.
// Endpoints are stored as vertex IDs to keep Graph storage compact and deterministic.
//
// Implementation:
//   - Stage 1: AddEdge constructs a baseline Edge with graph defaults.
//   - Stage 2: AddEdge applies EdgeOptions sequentially (first error aborts).
//   - Stage 3: Edge is registered in the edge catalog and adjacency is updated.
//
// Ownership / Mutation Law:
//   - Graph query methods may return *Edge aliases to catalog records.
//   - Once published in a Graph, Edge.ID, Edge.From, Edge.To, Edge.Weight, and
//     Edge.Directed MUST be treated as immutable by callers.
//   - If detached mutable ownership is required, callers must allocate their own copy.
//
// Behavior highlights:
//   - ID is unique within a graph for the graph lifetime.
//   - For undirected edges (Directed=false), adjacency is mirrored.
//
// Inputs:
//   - ID: unique edge identifier; auto-generated unless WithID is used.
//   - From/To: endpoint vertex IDs.
//   - Weight: must be 0 unless the graph is WithWeighted().
//   - Directed: effective directionality (may be overridden per-edge only in mixed mode).
//
// Returns:
//   - N/A (data type).
//
// Errors:
//   - N/A (data type).
//
// Determinism:
//   - Edge.ID is the stable ordering key for public enumeration.
//
// Complexity:
//   - N/A (data type).
//
// Notes:
//   - Auto-generated IDs are of the form "eN" where N is a monotonically increasing counter.
//
// AI-Hints:
//   - Treat returned *Edge pointers from getters as read-only to avoid data races.
type Edge struct {
	// ID is a unique string identifier for the edge (auto-generated by default, or provided via WithID).
	// Once published in a Graph, it MUST be treated as immutable.
	ID string

	// From is the source vertex ID (for undirected edges this is one endpoint).
	// Once published in a Graph, it MUST be treated as immutable.
	From string

	// To is the destination vertex ID (for undirected edges this is the other endpoint).
	// Once published in a Graph, it MUST be treated as immutable.
	To string

	// Weight is the edge cost/capacity; must be 0 unless the graph is WithWeighted().
	// Once published in a Graph, it MUST be treated as immutable.
	Weight float64

	// Directed = true means the edge is asymmetric (From -> To only).
	// Directed = false means the edge is symmetric (From <-> To, adjacency mirrored).
	// Once published in a Graph, it MUST be treated as immutable.
	Directed bool
}

// GraphOption mutates only a newly constructed Graph inside NewGraph.
//
// Implementation:
//   - Stage 1: NewGraph validates the option list shape and rejects nil option values.
//   - Stage 2: NewGraph allocates empty catalogs.
//   - Stage 3: Options are applied deterministically in call order.
//   - Stage 4: The configured graph is published only if every option succeeds.
//
// Behavior highlights:
//   - Options are construction-time only.
//   - Options MUST NOT panic as part of the public contract.
//   - A nil GraphOption is rejected with ErrNilGraphOption before invocation.
//   - Option implementations may mutate only the graph being constructed.
//
// Inputs:
//   - g: the graph instance being constructed.
//
// Returns:
//   - error: nil on success; otherwise a stable sentinel error.
//
// Errors:
//   - Nil option values are rejected by NewGraph/NewMixedGraph with ErrNilGraphOption.
//   - Option implementations may return stable sentinels for invalid configuration.
//
// Determinism:
//   - Deterministic application order (left-to-right).
//
// Complexity:
//   - Time O(1) per option, Space O(1).
//
// Notes:
//   - Core avoids hidden global state; behavior changes must be explicit via options.
//   - On constructor error, no partially configured graph is published to the caller.
//
// AI-Hints:
//   - Prefer explicit options over implicit defaults when writing reproducible tests.
//   - Return sentinels; do not panic or mutate external state from a GraphOption.
type GraphOption func(g *Graph) error

// WithDirected sets the default directedness for all future edges created in this graph.
// Per-edge overrides are only allowed in mixed mode (WithMixedEdges + WithEdgeDirected).
//
// Implementation:
//   - Stage 1: Store defaultDirected into g.directed during construction.
//
// Behavior highlights:
//   - Affects only the default for future edges (not existing edges).
//
// Inputs:
//   - defaultDirected: true for directed-by-default graphs; false for undirected-by-default.
//
// Returns:
//   - GraphOption: construction-time mutator.
//
// Errors:
//   - None.
//
// Determinism:
//   - Deterministic; constant-time flag set.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// Notes:
//   - Mixed mode controls whether individual edges may override Directed.
//
// AI-Hints:
//   - Use WithMixedEdges() if your workload needs both directed and undirected edges in one graph.
//   - Sets only the default; per-edge override requires WithMixedEdges().
func WithDirected(defaultDirected bool) GraphOption {
	return func(g *Graph) error {
		g.directed = defaultDirected
		return nil
	}
}

// WithWeighted enables non-zero edge weights in this graph.
//
// Implementation:
//   - Stage 1: Set g.weighted = true during construction.
//
// Behavior highlights:
//   - Without this option, AddEdge rejects weight != 0 with ErrBadWeight.
//
// Returns:
//   - GraphOption: construction-time mutator.
//
// Errors:
//   - None.
//
// Determinism:
//   - Deterministic; constant-time flag set.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// AI-Hints:
//   - Keep graphs unweighted if you only need topology; it simplifies inputs and tests.
//   - Without this, AddEdge(weight!=0) returns ErrBadWeight.
func WithWeighted() GraphOption {
	return func(g *Graph) error {
		g.weighted = true
		return nil
	}
}

// WithMultiEdges permits parallel edges between the same endpoints.
//
// Implementation:
//   - Stage 1: Set g.allowMulti = true during construction.
//
// Behavior highlights:
//   - Without this option, AddEdge on an existing (from,to) bucket returns ErrMultiEdgeNotAllowed.
//
// Returns:
//   - GraphOption: construction-time mutator.
//
// Errors:
//   - None.
//
// Determinism:
//   - Deterministic; constant-time flag set.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// AI-Hints:
//   - Enable multi-edges for multigraph models (e.g., multiple relations between entities).
//   - Without this, a second AddEdge(from,to,...) returns ErrMultiEdgeNotAllowed.
func WithMultiEdges() GraphOption {
	return func(g *Graph) error {
		g.allowMulti = true
		return nil
	}
}

// WithLoops permits self-loops (edges from a vertex to itself).
//
// Implementation:
//   - Stage 1: Set g.allowLoops = true during construction.
//
// Behavior highlights:
//   - Without this option, AddEdge(v,v,...) returns ErrLoopNotAllowed.
//
// Returns:
//   - GraphOption: construction-time mutator.
//
// Errors:
//   - None.
//
// Determinism:
//   - Deterministic; constant-time flag set.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// AI-Hints:
//   - Keep loops disabled unless your math model explicitly includes self transitions.
//   - Without this, AddEdge(v,v,...) returns ErrLoopNotAllowed.
func WithLoops() GraphOption {
	return func(g *Graph) error {
		g.allowLoops = true
		return nil
	}
}

// WithMixedEdges enables per-edge directedness overrides (mixed mode).
// In mixed mode, individual edges may specify Directed=true/false via EdgeOption.
//
// Implementation:
//   - Stage 1: Set g.allowMixed = true during construction.
//
// Behavior highlights:
//   - Without this option, WithEdgeDirected(...) returns ErrMixedEdgesNotAllowed.
//
// Returns:
//   - GraphOption: construction-time mutator.
//
// Errors:
//   - None.
//
// Determinism:
//   - Deterministic; constant-time flag set.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// AI-Hints:
//   - Mixed mode is a capability flag; keep it off if all edges share the same orientation.
func WithMixedEdges() GraphOption {
	return func(g *Graph) error {
		g.allowMixed = true
		return nil
	}
}

// EdgeOption configures a single edge during AddEdge.
//
// Implementation:
//   - Stage 1: AddEdge performs stateless validation, including nil EdgeOption rejection.
//   - Stage 2: AddEdge builds a baseline Edge (defaults + endpoints + weight).
//   - Stage 3: AddEdge applies EdgeOptions sequentially; the first error aborts edge publication.
//
// Behavior highlights:
//   - Options MUST NOT panic as part of the public contract.
//   - A nil EdgeOption is rejected with ErrNilEdgeOption before invocation.
//   - Options MUST NOT mutate global graph state as a side effect.
//   - Options should be O(1) and deterministic.
//
// Inputs:
//   - g: the owning graph (read-only for options; do not mutate global state).
//   - e: the edge being configured (options may mutate only this edge).
//
// Returns:
//   - error: nil on success; otherwise a sentinel error
//     (ErrMixedEdgesNotAllowed, ErrEmptyEdgeID, ErrEdgeIDConflict, ...).
//
// Errors:
//   - Nil option values are rejected by AddEdge with ErrNilEdgeOption before invocation.
//   - Non-nil options must return only stable sentinels (checked via errors.Is).
//
// Determinism:
//   - Deterministic given deterministic inputs; option order is call-order stable.
//
// Complexity:
//   - Time O(1) per option, Space O(1).
//
// Notes:
//   - AddEdge applies non-nil options under the edge/adjacency write lock;
//     options must not take additional locks.
//
// AI-Hints:
//   - Keep options “local”: modify only *e and validate against graph capability flags.
type EdgeOption func(g *Graph, e *Edge) error

// WithEdgeDirected overrides directedness for a single edge.
//
// Implementation:
//   - Stage 1: Validate that the graph was constructed with WithMixedEdges().
//   - Stage 2: Assign e.Directed = directed.
//
// Behavior highlights:
//   - Requires WithMixedEdges mode; otherwise returns ErrMixedEdgesNotAllowed.
//
// Inputs:
//   - directed: desired directedness for this edge.
//
// Returns:
//   - EdgeOption: per-edge mutator.
//
// Errors:
//   - ErrMixedEdgesNotAllowed: if the graph does not allow per-edge directedness overrides.
//
// Determinism:
//   - Deterministic; constant-time flag set.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// Notes:
//   - This option does not change endpoints; only directionality.
//
// AI-Hints:
//   - Use mixed mode only when you truly need both orientations in one graph.
func WithEdgeDirected(directed bool) EdgeOption {
	return func(g *Graph, e *Edge) error {
		// Mixed-mode is a construction-time capability flag (immutable after NewGraph).
		if !g.allowMixed {
			return ErrMixedEdgesNotAllowed
		}
		// Apply the per-edge override.
		e.Directed = directed
		return nil
	}
}

// WithID assigns a custom identifier to the edge created by AddEdge.
//
// Implementation:
//   - Stage 1: Validate id is non-empty (ErrEmptyEdgeID).
//   - Stage 2: Under AddEdge's edge lock, check the edge catalog for collisions (ErrEdgeIDConflict).
//   - Stage 3: Set e.ID = id.
//   - Stage 4: If id matches the canonical auto-ID form "eN", bump the auto-ID counter
//     so that future auto-generated IDs never collide with the explicit "eN".
//
// Behavior highlights:
//   - Works regardless of mixed mode.
//   - Deterministic: collision is a strict membership check, not a scan.
//
// Inputs:
//   - id: desired edge identifier; must be non-empty and globally unique within the graph.
//
// Returns:
//   - EdgeOption: per-edge mutator.
//
// Errors:
//   - ErrEmptyEdgeID: if id == "".
//   - ErrEdgeIDConflict: if id is already present in the edge catalog.
//
// Determinism:
//   - Deterministic; does not depend on map iteration order.
//
// Complexity:
//   - Time O(1), Space O(1).
//
// Notes:
//   - If you choose IDs of the canonical auto form "eN", the graph will advance its auto-ID counter past N.
//
// AI-Hints:
//   - Use WithID for stable external references (golden tests, trace correlation, interop).
//   - Prefer non-auto-shaped IDs (e.g., "road_A_B") when you do not want to affect the auto-ID counter.
func WithID(id string) EdgeOption {

	return func(g *Graph, e *Edge) error {
		// Reject empty identifiers.
		if id == "" {
			return ErrEmptyEdgeID
		}

		// AddEdge applies options under muEdgeAdj write lock, so reading g.edges is safe here.
		if _, exists := g.edges[id]; exists {
			return ErrEdgeIDConflict
		}

		// Assign the custom identifier.
		e.ID = id

		// If the explicit ID looks like an auto-generated "eN", bump the counter to avoid collisions.
		if num, ok := matchesAutoIDPattern(e.ID); ok && num >= 0 {
			bumpNextEdgeIDToAtLeast(g, num)
		}

		return nil
	}
}

// Graph is a thread-safe, deterministic in-memory graph.
//
// Concurrency model:
//   - muVert protects vertex-level state (vertices map).
//   - muEdgeAdj protects edges map and adjacencyList.
//   - Locks are separated to reduce contention in algorithms that iterate neighbors frequently.
//
// Storage model:
//   - vertices: map[string]*Vertex - vertex catalog by ID.
//   - edges:    map[string]*Edge   - edge catalog by unique Edge.ID.
//   - adjacencyList: map[fromID]map[toID]map[edgeID]struct{} for O(1) membership.
//
// Configuration flags:
//   - directed/weighted/allowMulti/allowLoops/allowMixed are set only during construction
//     and remain immutable afterwards.
//
// ID generation:
//   - Auto edge IDs are "eN" where N is a monotonically increasing counter.
//   - WithID/SetEdgeID bump the counter when assigning canonical "eN" IDs.
//
// Determinism:
//   - Public enumeration order is stable and documented at package level.
//
// Notes:
//   - Clone is expected to carry over the counter to prevent collisions.
type Graph struct {
	// muVert guards vertex map and configuration flags to allow safe, low-contention reads.
	muVert sync.RWMutex

	// muEdgeAdj guards edge catalog and adjacency list for consistent graph topology updates.
	muEdgeAdj sync.RWMutex

	// Configuration flags (read under muVert; written only during construction).
	directed   bool // default directedness for future edges
	weighted   bool // allow non-zero weights
	allowMulti bool // allow parallel edges
	allowLoops bool // allow self-loops
	allowMixed bool // allow per-edge directedness overrides (mixed mode)

	// nextEdgeID is the next sequential ID number to use for auto-generated edge IDs.
	// It is incremented atomically. Custom edge IDs (via WithID) overwrite ID, but don't change the counting process.
	nextEdgeID uint64

	// Vertex catalog: ID -> *Vertex (caller-visible IDs, stable across runtime).
	vertices map[string]*Vertex

	// Edge catalog: EdgeID -> *Edge (unique identities across the graph’s lifetime).
	edges map[string]*Edge

	// Adjacency: fromID -> toID -> edgeID -> unit. Provides O(1) membership checks
	// and deterministic extraction (final sorting happens at API boundaries).
	adjacencyList map[string]map[string]map[string]struct{}
}

// GraphStats is a read-only result object summarizing graph state.
//
// Implementation:
//   - Filled by (*Graph).Stats() by scanning catalogs (implementation elsewhere).
//
// Behavior highlights:
//   - Pure data type: no methods, no side effects.
//
// Determinism:
//   - Field meanings are stable and part of the public contract.
//
// Complexity:
//   - N/A (data type).
//
// AI-Hints:
//   - Use Stats() in tests as a deterministic admission check (counts, feature flags).
type GraphStats struct {
	// DirectedDefault is the graph-wide default orientation (true=directed).
	DirectedDefault bool

	// Weighted is true when non-zero edge weights are permitted.
	Weighted bool

	// AllowsMulti is true when parallel edges are permitted.
	AllowsMulti bool

	// AllowsLoops is true when self-loops are permitted.
	AllowsLoops bool

	// MixedMode is true when per-edge Directed overrides are permitted.
	MixedMode bool

	// VertexCount is the number of vertices present in the graph.
	VertexCount int

	// EdgeCount is the number of edges present in the graph.
	EdgeCount int

	// DirectedEdgeCount is the number of edges with Directed == true.
	DirectedEdgeCount int

	// UndirectedEdgeCount is the number of edges with Directed == false.
	UndirectedEdgeCount int
}

// NewGraph constructs an empty graph and applies GraphOption values deterministically.
//
// Implementation:
//   - Stage 1: Validate the option list shape and reject nil GraphOption values.
//   - Stage 2: Allocate empty vertex/edge catalogs and adjacency map.
//   - Stage 3: Apply options in call order (left-to-right).
//   - Stage 4: Publish the fully configured graph on success only.
//
// Behavior highlights:
//   - Construction-time options only; subsequent behavior is controlled by method contracts.
//   - nextEdgeID starts at 0; the first auto-generated edge becomes "e1".
//   - Constructor validation is part of the public contract; no panic-based option handling.
//
// Inputs:
//   - opts: zero or more GraphOption values applied in call order.
//
// Returns:
//   - *Graph: configured empty graph on success.
//   - error: nil on success; otherwise a stable sentinel error.
//
// Errors:
//   - ErrNilGraphOption: if opts contains a nil GraphOption value.
//   - Any stable sentinel returned by a provided GraphOption.
//
// Determinism:
//   - Deterministic option validation order and deterministic option application order.
//
// Complexity:
//   - Time O(len(opts)), Space O(1) excluding map growth.
//
// Notes:
//   - Nil GraphOption validation happens before graph allocation and publication.
//   - On error, no partially configured graph is returned to the caller.
//
// AI-Hints:
//   - Keep option sets explicit to make tests reproducible.
//   - Check the returned error with errors.Is; do not rely on panic recovery.
func NewGraph(opts ...GraphOption) (*Graph, error) {
	// Allocate a new Graph with empty maps; sizes grow amortized O(1).
	g := &Graph{
		vertices:      make(map[string]*Vertex),
		edges:         make(map[string]*Edge),
		adjacencyList: make(map[string]map[string]map[string]struct{}),
	}

	var opt GraphOption
	for _, opt = range opts {
		// nil validating
		if opt == nil {
			return nil, ErrNilGraphOption
		}
		// options setter
		if err := opt(g); err != nil {
			return nil, err
		}
	}

	return g, nil
}

// Nilable provides an explicit, reflect-free mechanism to treat typed-nil receivers
// stored inside interfaces as nil during validation and testing.
//
// Implementation:
//   - Stage 1: Callers accept an interface value that may hold a typed nil pointer.
//   - Stage 2: If the dynamic value implements Nilable, callers invoke IsNil().
//   - Stage 3: If IsNil reports true, the value is treated as nil by the caller.
//
// Behavior highlights:
//   - Avoids reflect in foundational validators and test helpers.
//   - Keeps nil-detection O(1) and deterministic.
//   - Optional: types that do not implement Nilable are checked with regular `== nil`.
//
// Returns:
//   - bool: true if the receiver should be treated as nil.
//
// Errors:
//   - None. IsNil MUST NOT panic and MUST NOT allocate.
//
// Determinism:
//   - Deterministic and side-effect free (required).
//
// Complexity:
//   - Time O(1), Space O(1).
//
// Notes:
//   - In Go, an interface can be non-nil while holding a typed nil pointer.
//
// AI-Hints:
//   - Implement IsNil() on pointer-backed types that are commonly stored behind interfaces.
type Nilable interface {
	// IsNil reports whether the receiver should be treated as nil.
	// It MUST be side-effect free, deterministic, non-allocating, and MUST NOT panic.
	IsNil() bool
}
